#include "rFusionAlgs.h"
#include "rColorTerm.h"
#include "rAlgConfigFile.h"
#include "rOS.h"

using namespace rapio;

void
RAPIOFusionAlgs::declareOptions(RAPIOOptions& o)
{
  o.setDescription("RAPIO Fusion Stage Three Algorithm. Fuses 3D algorithms into parallel spatial chunks.");
  o.setAuthors("Robert Toomey");

  // Optional: Let user define thread count, default to hardware concurrency
  o.optional("threads", std::to_string(std::thread::hardware_concurrency()), "Number of spatial threads to use");
}

void
RAPIOFusionAlgs::processOptions(RAPIOOptions& o)
{
  // 1. The controller's own options (like 'threads') are already parsed and ready!
  size_t threads = o.getInteger("threads");

  fLogInfo("FusionAlgs configuring with {} threads", threads);

  // 2. Check if an XML config was provided to the orchestrator
  // Note that this file gets read twice.  Once for main fusionAlg parameters,
  // and then again for the children algs here.
  std::string configFile = o.getString("iconfig");

  if (configFile.empty()) {
    fLogSevere("FusionAlgs requires an -iconfig XML file to load its child algorithms.");
    exit(1);
  }

  // FIXME: Maybe we do this in firstTimeData, not sure.
  URL configUrl(configFile);
  auto configParser = AlgConfigFile::getConfigFileForURL(configUrl);

  if (!configParser) {
    fLogSevere("No configuration parser found for {}", configFile);
    exit(1);
  }

  // 3. Extract the sub-algorithms from the same file
  std::vector<AlgConfigNode> algNodes;

  if (!configParser->readMultiConfigURL(configUrl, algNodes)) {
    fLogSevere("Failed to read multi-algorithm configuration from {}", configFile);
    exit(1);
  }

  // 4. Spin up the children
  for (const auto& node : algNodes) {
    fLogInfo("Loading dynamic child '{}' from '{}'", node.name, node.library);

    auto basePtr   = OS::loadDynamic<RAPIOAlgorithm>(node.library, "createRAPIOAlg");
    auto volumeAlg = std::dynamic_pointer_cast<VolumeAlgorithm>(basePtr);

    if (volumeAlg) {
      RAPIOOptions scopedOptions(node.name);
      volumeAlg->declareOptions(scopedOptions);

      for (size_t i = 0; i < node.options.size(); ++i) {
        scopedOptions.storeParsedArg(node.options[i], node.values[i], false, true);
      }

      scopedOptions.setIsProcessed();

      volumeAlg->processOptions(scopedOptions);
      myLoadedAlgorithms.push_back(volumeAlg);
    } else {
      fLogSevere("Failed to load or cast child algorithm '{}'", node.name);
    }
  }
} // RAPIOFusionAlgs::processOptions

void
RAPIOFusionAlgs::firstDataSetup()
{ }

void
RAPIOFusionAlgs::processNewData(rapio::RAPIOData& d)
{
  // firstDataSetup();

  auto llg = d.datatype<rapio::LatLonHeightGrid>();

  if (llg != nullptr) {
    fLogInfo("{}{}---Stage3 (Fused Execution)---{}", ColorTerm::green(), ColorTerm::bold(), ColorTerm::reset());
    if (myLoadedAlgorithms.empty()) {
      fLogSevere("No algorithms loaded! Did you provide a valid pipeline XML via -iconfig?");
      return;
    }

    auto compositeCb = std::make_shared<MultiHeightGridCallback>();

    // 3. Keep unique_ptrs alive for the lifespan of the thread execution!
    std::vector<std::unique_ptr<LatLonHeightGridCallback> > activeCallbacks;

    // Loop dynamically over however many algorithms we loaded via XML
    for (auto& alg : myLoadedAlgorithms) {
      alg->checkOutputGrids(llg);
      auto cb = alg->createCallback();
      if (cb) {
        compositeCb->addCallback(cb.get());
        activeCallbacks.push_back(std::move(cb)); // Transfers ownership to our safe vector
      }
    }

    if (activeCallbacks.empty()) {
      fLogSevere("No valid callbacks were generated by the loaded algorithms.");
      return;
    }

    size_t totalRows  = llg->getNumLats();
    size_t numThreads = std::thread::hardware_concurrency();
    if (numThreads == 0) { numThreads = 4; }

    // Safety check just in case we have fewer rows than threads
    if (numThreads > totalRows) { numThreads = totalRows; }

    size_t rowsPerThread = totalRows / numThreads;

    ThreadGroup threadPool(numThreads, numThreads * 2);
    std::vector<std::shared_ptr<GridChunkTask> > tasks;

    for (size_t i = 0; i < numThreads; ++i) {
      size_t startY = i * rowsPerThread;
      size_t endY   = (i == numThreads - 1) ? totalRows : startY + rowsPerThread;

      auto task = std::make_shared<GridChunkTask>(llg, compositeCb, startY, endY);
      tasks.push_back(task);
      threadPool.enqueueThreadTask(task);
    }

    for (auto& task : tasks) {
      task->waitUntilDone();
    }

    // Write out the products dynamically
    for (auto& alg : myLoadedAlgorithms) {
      alg->writeFinalProducts(this);
    }
  }
} // RAPIOFusionAlgs::processNewData

void
RAPIOFusionAlgs::processHeartbeat(const Time& n, const Time& p)
{
  if (isDaemon()) {
    fLogInfo("{}{}---Heartbeat---{}", ColorTerm::green(), ColorTerm::bold(), ColorTerm::reset());
  }
}

int
main(int argc, char * argv[])
{
  RAPIOFusionAlgs alg = RAPIOFusionAlgs();

  alg.executeFromArgs(argc, argv);
}
