#!/bin/sh
# Toomey Jul 2021

# Predefined settings and functions
. ./config.sh

# If you make your own algorithm, give full container path like so:
# /BUILD/MYALGS/Algname/binary
dockerrun "--rm rapio:f34 rsimplealg" "$@"
