#include "rMaxAGL.h"
#include "rIODataType.h"
#include <algorithm>

using namespace rapio;

void
MaxAGL::declareOptions(RAPIOOptions& o)
{
  o.setDescription("Calculates the maximum value in a column from ground to a specified AGL height.");
  o.setAuthors("Robert Toomey");
  o.require("terrain", "", "Path to the NetCDF terrain generated by rTerrainFetch (Can be different resolution)");
  o.optional("topaglkm", "4.0", "Top height AGL in kilometers to search up to (default 4km)");
  declareProduct("MaxAGL", "Max value from ground to top agl");
}

void
MaxAGL::processOptions(RAPIOOptions& o)
{
  myTerrainFile = o.getString("terrain");
  myTopAglKMs   = o.getFloat("topaglkm");
}

void
MaxAGL::loadTerrainGrid()
{
  // Only load the terrain NetCDF once
  if (myTerrainGrid == nullptr) {
    fLogInfo("Loading terrain grid from {}...", myTerrainFile);

    myTerrainGrid = IODataType::read<LatLonGrid>(myTerrainFile);
    if (myTerrainGrid == nullptr) {
      fLogSevere("Failed to load terrain grid at {}. MaxAGL cannot proceed.", myTerrainFile);
      exit(1);
    }

    // We use a projection so we can safely query the terrain even if the
    // radar grid and the terrain grid bounds/resolutions aren't perfectly 1:1 identical.
    myTerrainProj = std::make_shared<LatLonGridProjection>(Constants::PrimaryDataName, myTerrainGrid.get());
  }
}

void
MaxAGL::processNewData(RAPIOData& d)
{
  // We only care about 3D data cubes
  auto llg = d.datatype<LatLonHeightGrid>();

  if (llg != nullptr) {
    processVolume(llg);
  }
}

void
MaxAGL::processVolume(std::shared_ptr<LatLonHeightGrid> input)
{
  loadTerrainGrid();

  const Time forTime = input->getTime();
  const LLCoverageArea coverage = input->getLLCoverageArea();

  // Rebuild the output grid if the coverage area changes (or on first run)
  if ((myMaxGrid == nullptr) || (myCachedCoverage != coverage)) {
    fLogInfo("Creating new output grid for MaxAGL (0-{} km AGL)...", myTopAglKMs);
    myMaxGrid = LatLonGrid::Create("MaxAGL", input->getUnits(), forTime, coverage);

    char subTypeBuf[32];
    snprintf(subTypeBuf, sizeof(subTypeBuf), "0-%.1fkm", myTopAglKMs);
    myMaxGrid->setDataAttributeValue("SubType", subTypeBuf);

    // Attempt to borrow the colormap from the input (e.g. Reflectivity colors)
    std::string colorMap;
    if (input->getString("ColorMap-value", colorMap)) {
      myMaxGrid->setDataAttributeValue("ColorMap", colorMap);
    }
    myCachedCoverage = coverage;
  }

  myMaxGrid->setTime(forTime);

  const size_t numLats = input->getNumLats();
  const size_t numLons = input->getNumLons();
  const size_t numHts  = input->getNumLayers();

  auto& grid3D = input->getFloat3DRef();
  auto& max2D  = myMaxGrid->getFloat2DRef();

  // Cache the height levels in kilometers for fast comparison
  std::vector<float> hlevels(numHts);

  for (size_t h = 0; h < numHts; h++) {
    hlevels[h] = input->getLayerValue(h) / 1000.0f; // Convert meters to km
  }

  AngleDegs deltaLat = input->getLatSpacing();
  AngleDegs deltaLon = input->getLonSpacing();
  LLH nw = input->getTopLeftLocationAt(0, 0);
  AngleDegs startLat = nw.getLatitudeDeg() - (deltaLat / 2.0);
  AngleDegs startLon = nw.getLongitudeDeg() + (deltaLon / 2.0);

  AngleDegs atLat = startLat;

  for (size_t i = 0; i < numLats; ++i, atLat -= deltaLat) {
    AngleDegs atLon = startLon;
    for (size_t j = 0; j < numLons; ++j, atLon += deltaLon) {
      // 1. Get Terrain MSL at this coordinate
      double terrHeightM = myTerrainProj->getValueAtLL(atLat, atLon);
      float terrHeightKm = (!Constants::isGood(terrHeightM)) ? 0.0f : (terrHeightM / 1000.0f);

      // 2. Define our vertical window
      float topSearchHeightKm = terrHeightKm + myTopAglKMs;

      float maxVal    = -999999.0f;
      bool foundValid = false;

      // 3. Scan the column
      for (size_t k = 0; k < numHts; ++k) {
        float currentHtKm = hlevels[k];

        // Check if this level falls inside the [Ground, Ground + 4km] window
        if ((currentHtKm >= terrHeightKm) && (currentHtKm <= topSearchHeightKm)) {
          float v = grid3D[k][i][j];
          if (Constants::isGood(v)) {
            if (!foundValid || (v > maxVal)) {
              maxVal     = v;
              foundValid = true;
            }
          }
        }
      }

      // 4. Assign the max value (or missing if column was completely empty)
      max2D[i][j] = foundValid ? maxVal : Constants::MissingData;
    }
  }

  // Write the output!
  std::map<std::string, std::string> extraParams;

  writeOutputProduct("MaxAGL", myMaxGrid, extraParams);
} // MaxAGL::processVolume
