#pragma once
#include <rDataType.h>
#include <rTimeDuration.h>
#include <rTime.h>
#include <vector>
#include <memory>
#include <string>

namespace rapio {
/**
 * @class DataTypeGroup
 * @ingroup rapio_data
 * @brief A generalized container for managing and time-purging a collection of DataTypes.
 *
 * DataTypeGroup serves as the base class for collections like Volumes (grouped by elevation)
 * or ProductGroups (grouped by TypeName). It provides automated time-window expiration,
 * which can fall back to the global algorithm history or use a custom override for
 * slow-updating environmental data.
 * @author Robert Toomey
 */
class DataTypeGroup {
public:

  /**
   * @brief Construct a new DataType Group using the global algorithm time window.
   * @param k The unique key identifying this group.
   */
  DataTypeGroup(const std::string& k);

  /**
   * @brief Construct a new DataType Group with a custom time window override.
   * @param k The unique key identifying this group.
   * @param customWindow The specific TimeDuration to keep data alive.
   */
  DataTypeGroup(const std::string& k, const TimeDuration& customWindow);

  virtual
  ~DataTypeGroup() = default;

  /**
   * @brief Generates the unique key for a given DataType within this group.
   * @param dt The DataType to evaluate.
   * @return A string representing the unique key (e.g., SubType, TypeName).
   */
  virtual std::string
  generateItemKey(const std::shared_ptr<DataType>& dt) const = 0;

  /**
   * @brief Adds a DataType to the group. Implemented by subclasses.
   * @param dt The DataType to add.
   */
  virtual void
  addDataType(std::shared_ptr<DataType> dt) = 0;

  /**
   * @brief Purges items from the group that are older than the allowed time window.
   * @param currentTime The current simulation or wall-clock time.
   */
  virtual void
  purgeTimeWindow(const Time& currentTime);

  /**
   * @brief Retrieves a stored DataType matching the specified key.
   * @param key The item key generated by generateItemKey.
   * @return Shared pointer to the DataType, or nullptr if not found.
   */
  std::shared_ptr<DataType>
  getDataType(const std::string& key) const;

  /**
   * @brief Removes a stored DataType matching the specified key.
   * @param key The item key generated by generateItemKey.
   * @return True if the item was found and removed, false otherwise.
   */
  bool
  removeDataType(const std::string& key);

  /**
   * @brief Clears all items from the group.
   */
  void
  clearGroup();

  /**
   * @brief Gets the identifier key for this group.
   * @return The group key.
   */
  std::string
  getKey() const;

  /**
   * @brief Gets the underlying vector of DataTypes.
   * @return Constant reference to the item vector.
   */
  const std::vector<std::shared_ptr<DataType> >&
  getItems() const;

protected:
  std::string myKey;                               ///< The identifier for this group.
  std::vector<std::shared_ptr<DataType> > myItems; ///< The stored collection of DataTypes.
  TimeDuration myCustomWindow;                     ///< The custom expiration window (if set).
  bool myUseCustomWindow;                          ///< Flag indicating if the custom window is used.
};

/**
 * @class ProductGroup
 * @ingroup rapio_data
 * @brief A concrete DataTypeGroup that categorizes data by its TypeName.
 *
 * Ideal for storing environmental or NSE grids where the product name (e.g., "Heightof-10C")
 * dictates uniqueness.
 * @author Robert Toomey
 */
class ProductGroup : public DataTypeGroup {
public:
  ProductGroup(const std::string& k) : DataTypeGroup(k){ }

  ProductGroup(const std::string& k, const TimeDuration& customWindow) : DataTypeGroup(k, customWindow){ }

  virtual std::string
  generateItemKey(const std::shared_ptr<DataType>& dt) const override;
  virtual void
  addDataType(std::shared_ptr<DataType> dt) override;
};
} // namespace rapio
